pipeline {
	agent any
	
	environment{
		dockerHome = tool 'myDocker'
		mavenHome = tool 'myMaven'
		PATH = "$mavenHome/bin:$dockerHome/bin:$PATH"
	}
	stages{
		stage('Checkout'){
			steps{
				echo "$PATH"
				echo "$env.WORKSPACE"
				echo "$env.JENKINS_HOME"
			}	
		}
		stage('Compile') {
			steps{
			 dir("$env.WORKSPACE/currency-exchange-microservice/"){
				sh "mvn clean compile"
				}
			echo "Compile"
			}
			
		}
		stage('Test') {
			steps{
			echo "Test"
			 dir("$env.WORKSPACE/currency-exchange-microservice/"){
				sh "mvn test"
				}
			}
		}
		stage('Integration Test') {
			steps{
			echo "Integration Test"
			dir("$env.WORKSPACE/currency-exchange-microservice/"){
			sh "mvn failsafe:Integration test failsafe:verify"
				}
			
			}
		}		
	}
	post{
		always{
			echo "I run always"
		}
		success{
			echo "I run when the build is successful"
		}
		failure{
			echo "I run when the build has failed"
		}
	}
}
