pipeline {
	agent any
	
	stages{
		stage('Build') {
			echo "Build"
		}
		stage('Test') {
			echo "Test"
		}
		stage('Integration Test') {
			echo "Integration Test"
		}		
	}
	post{
		always{
			echo "I run always"
		}
		sucess{
			echo "I run when the build is successful"
		}
		failure{
			echo "I run when the build has failed"
		}
	}
}
