pipeline {
	agent any
	
	environment{
		dockerHome = tool 'myDocker'
		mavenHome = tool 'myMaven'
		PATH = "$mavenHome/bin:$dockerHome/bin:$PATH"
	}
	stages{
		stage('Compile') {
			steps{
			sh "cd currency-exchange-microservice"
			sh "mvn clean compile"
			echo "Compile"
			}
			
		}
		stage('Test') {
			steps{
			echo "Test"
			sh "mvn test"
			}
		}
		stage('Integration Test') {
			steps{
			echo "Integration Test"
			sh "mvn failsafe:Integration test failsafe:verify"
			}
		}		
	}
	post{
		always{
			echo "I run always"
		}
		success{
			echo "I run when the build is successful"
		}
		failure{
			echo "I run when the build has failed"
		}
	}
}
